import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "../../components/ui/sidebar";
import { AppSidebar } from "../../components/reuseable/app-sidebar";
import Navbar from "../../components/reuseable/Navbar";
import LenisProvider from "@/components/providers/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lenis Animation Dashboard",
  description: "Generated by create me",
  icons: {
    icon: "/images/mainlogo.png",
    apple: "/images/mainlogo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full">
              <Navbar />
              <SidebarTrigger className="fixed top-1 left-1 z-10 left-4 text-white md:hidden block" />
              {children}
            </main>
          </SidebarProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
